### ISSUE TITLE
Documentation on correlating a swingtime model with my own models. 

### ISSUE THREAD

**Issue by greenleafone7** [dakrauth/django-swingtime#13]
Would it be possible to update the documentation with some examples on how to correlate the models that swingtime provides with my own. So for example one would be able to have specific events for different users. 

Or possibly edit the karate example to showcase such functionality. Thinking about it, a nice feature would be email notifications for expiring events. I don't know if this exists already in Django, I am just throwing it as an idea.

Thanks.

**Comment by dakrauth** [comment]
I believe these are features outside of the scope of the project. A reasonable approach would be to set up a Celery (or some such) task to handle this expiring events.
