### ISSUE TITLE
Swingtime migrations 

### ISSUE THREAD

**Issue by LiamK** [dakrauth/django-swingtime#17]
I have an existing application that augments swingtime.Event by inheriting from it.  This has worked, but I'm running into issues as I upgrade to Django 1.9 (from Django 1.3).  There are no swingtime migrations.  Not sure what the best way to handle this would be.

Also +1 for the idea of documenting how to extend swingtime.  I wonder if providing an Abstract model would be possible.  I think that would simplify the migration issue.

**Comment by dakrauth** [comment]
I believe the most immediate solution was to add the migrations, plus run tests for Django 1.9, so I've upload version 0.7.

**Comment by dakrauth** [comment]
I will play around with the idea of Abstract models, but am not sure yet how that would affect the typical user. I'm not so sure all the Models would work as abstractions, which may only be a partial solution. For now, I think being able to use model inheritance or other forms of encapsulation should be sufficient.

**Comment by ampled** [comment]
I tried updating to 0.7 via pip and it seems the migrations folder wasn't included. Tried uninstalling and reinstalling, but still couldn't locate the migrations.

I'll try to install manually from the git repo, but just a heads up in case you forgot something.


I'll also throw in a +1 for a guide to extend swingtime properly (adding extra fields to events and such.)

**Comment by dakrauth** [comment]
Sorry, my setup.py file didn't handle the migrations directory. I've uploaded v0.7.1 to PyPI now with the fix.
